BACKBONE:
  NAME: 'clip'
  FILE: 'RN50x4_clip.pt'   
  FINETUNE: False
  LAYERS_TO_EXTRACT: ['layer1.3.relu3','layer2.5.relu3','layer3.9.relu3','layer4.5.relu3']
  PERCENT_OF_CHANNELS: 100
  INPUT_SIZE: (288,288)

TRAIN:
  BATCH_SIZE: 4
  MAX_EPOCHS: 10
  
DREAMS:
  ROTATE: 1.0
  TRANSLATE: (0.1,0.1)
  LR: 1e-2
  THRESHOLDS: (1500,)
  SCALE: (0.4,0.8)
